# Tables

We will learn how to manipulate data organized in tables in linux.

Make sure you are in your "~/linux" directory.

We will use the table you created called "part.cdc.seqs.len.both.txt". The columns or fields the read1name, read1length, read2name, read2length. No column headers are present.

Take a look at the file using cat, more, or less.

## Columns

You can grab columns (fields) from a file using "cut" or "awk" (**A**ho, **W**einberger and **K**ernighan; authors of the language) or "bioawk".

Get the read2 length (column 4) from part.cdc.seqs.len.both.txt.

```{bash, eval=FALSE}
cut -f4 part.cdc.seqs.len.both.txt
```

In "awk" (or "bioawk") it looks like this.

```{bash, eval=FALSE}
awk '{print $4}' part.cdc.seqs.len.both.txt

bioawk '{print $4}' part.cdc.seqs.len.both.txt
```

You can even rearrange the columns. Let's get the length of read1, the length of read2, and then the sequence name. The "\t" prints a tab.

```{bash, eval=FALSE}
cut -f 2,4,1 part.cdc.seqs.len.both.txt

awk '{print $2 "\t" $4 "\t" $1}' part.cdc.seqs.len.both.txt

bioawk '{print $2 "\t" $4 "\t" $1}' part.cdc.seqs.len.both.txt
```

Awk (and bioawk) allow you to do mathematical operations on columns as well. Let's find the difference between the read lengths (read1length-read2length).

```{bash, eval=FALSE}
awk '{print $4-$2}' part.cdc.seqs.len.both.txt
```

By default, the "awk" command splits fields on any combination of whitespace, including tabs and spaces. The "cut" command splits fields at tabs. Let's look at a file with both spaces and tabs.

The file has prevalences (percentages of people) with chronic diseases. In this case we are looking at data on adults ages 18+ in the U.S. that is derived from [here](https://www.cdc.gov/pcd/issues/2025/24_0539.htm).

Link to the file.

```{bash, eval=FALSE}
ln -s /home/data/nise/chronic_prevalence_US_adult.txt .
```

Take a look at the file.

```{bash, eval=FALSE}
cat chronic_prevalence_US_adult.txt
```

There are 3 columns:  
Chronic condition (disease name)  
2013 18+ (the prevalence of the disease in U.S. adults in 2013)  
2013 18+ (the prevalence of the disease in U.S. adults in 2023)


Get the second using both "cut".

```{bash, eval=FALSE}
cut -f 2 chronic_prevalence_US_adult.txt
```

Now get it with awk and compare.

```{bash, eval=FALSE}
awk '{print $2}' chronic_prevalence_US_adult.txt
```

The "awk" command is splitting each word in the chronic disease name into its own column.

But you can set the delimiter explicitly using the "-F" (field separator) parameter, telling "awk" to only split on tabs.

```{bash, eval=FALSE}
awk -F "\t" '{print $2}' chronic_prevalence_US_adult.txt
```

You can also change the delimiter for "cut" with the "-d" (delimiter) parameter. For example, "-d," will split fields based on commas.

## Viewing tables

To get the columns to line up better, use the "column" command. The "-t" parameter tells it to print the file in "table" format. The default is to split on whitespace but we can change that with the "-s" parameter. For tabs, you need to put a "$" before the tab ("\t") notation. Otherwise, it will split it at every "t".


```{bash, eval=FALSE}
column -t -s $'\t' chronic_prevalence_US_adult.txt
```

## Searching within columns

If we want to find which rows in the "chronic_prevalence_US_adult.txt" file contain "disease", we can do it with "grep", which you learned earlier.

```{bash, eval=FALSE}
grep "disease" chronic_prevalence_US_adult.txt
```

<!-- gff is an example-->
There are some instances, however, where you want to find rows with a match in a specific column. You can do that with "awk" using an if statement before the curly brackets. If it finds the word "disease" within column 1, it will print it.

```{bash, eval=FALSE}
awk -F "\t" '$1~/disease/{print}' chronic_prevalence_US_adult.txt
```

You can also filter based on the numbers. The following will get all rows where the 2023 prevalence is >=10%.

```{bash, eval=FALSE}
awk -F "\t" '$3>=10{print}' chronic_prevalence_US_adult.txt
```

If you want to find rows with a 2023 prevelance between 10% and 20% (inclusive), you can do both in the same command.

```{bash, eval=FALSE}
awk -F "\t" '$3>=10&&$3<=20{print}' chronic_prevalence_US_adult.txt
```


:::work
1) Calculate how much each chronic disease changed between 2013 and 2023 using awk.
+ The output should include the chronic disease name, the 2013 prevalence, the 2023 prevalence, and the difference.

2) Print out only lines where the prevalence went down (the difference is negative).
:::


## Substitutions

You can perform substitutions using "sed" (**S**tream **ED**itor). The format is:

sed "s/thing_to_sub_out/thing_to_sub_in/g"

The g ("global") at the end tells sed to make all the substitutions it can on each line and not just the first one.

Let's get the 3rd column from the sequence name line of the read1 fastq file. We'll use the one that we created earlier with the first 10 names ("cdc.names.r1.txt").

```{bash, eval=FALSE}
cut -f 3 cdc.names.r1.txt
```

This field has the length in it but it also has text ("length="). Let's substitute that out and replace it with nothing. We don't need the "g" qualifier since there is only one instance per line.

```{bash, eval=FALSE}
cut -f 3 cdc.names.r1.txt | sed "s/length=//"
```


## Sort

We can sort files using the "sort" command.

Numerically ("-n") sort the read1 length column (column 2) ("-k2") from shortest to longest.

```{bash, eval=FALSE}
sort -nk2 part.cdc.seqs.len.both.txt
```

Reverse ("-r") the order.

```{bash, eval=FALSE}
sort -nrk2 part.cdc.seqs.len.both.txt
```

Numerically ("-n") sort the read2 length column ("-k4") from shortest to longest.

```{bash, eval=FALSE}
sort -nk4 part.cdc.seqs.len.both.txt
```

Reverse ("-r") the order.

```{bash, eval=FALSE}
sort -nrk4 part.cdc.seqs.len.both.txt
```

## Unique

You can also find the unique values using the "uniq" command. The fastq files contained trimmed reads meaning that low quality sequence data has been trimmed back from the ends of the reads resulting in shorter sequences. Let's see what sequence lengths we have for read1 (column 2).

> **_NOTE:_** The "uniq" command assumes the values are sorted so get in the habit of sorting before finding uniq values.

```{bash, eval=FALSE}
cut -f2 part.cdc.seqs.len.both.txt | sort -n | uniq
```

We can also count how many of each unique value there are using the "-c" flag.

```{bash, eval=FALSE}
cut -f2 part.cdc.seqs.len.both.txt | sort -n | uniq -c
```


## Jeopardy

https://jeopardylabs.com/play/linux-commands-how-to




